# Generated by Django 2.2.4 on 2019-08-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail')),
                ('assunto', models.TextField(max_length=30, verbose_name='Assunto')),
                ('mensagem', models.TextField(max_length=255, verbose_name='Mensagem')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
